### PR TITLE
Added collision detection

### LINKED ISSUE #43: Add Collision Detection
## Expected Behaviour
Sherry should not be able to phase through the walls and desk. 
## Actual Behaviour
The edges of the room and the objects can be easily ignored. 
## Steps to Reproduce Behaviour
1. Walk up to a wall and walk through it. 
2. Walk through the desk.

### PR DESCRIPTION
**Pull request by Alice-Jaffray**
**Description of work.**

When Sherry walks up to the desk or wall he bounces back instead of going through desk/wall.

**To test:**

Start the game, check Sherry doesn't go through the desk or wall.

Fixes #43

### CODE REVIEW

**Review by cailafinn — CHANGES_REQUESTED** [review]
A few notes on this one:
- Sherry is able to leave through the bottom and side walls.
- The collisions with the wall or desk can push sherry "off-grid", meaning they no longer line up with the scenery properly. 
- Sometimes when walking into the bottom of the desk, Sherry is pushed to the side instead

It may be preferable to have a more free movement option for sherry instead of the grid movement. This might fix some of our bouncing issues.

**Comment by cailafinn** [comment]
Follow up: 
```
public class SherryMovement : MonoBehaviour
{
    // Publically Acessible variables
    public float walkSpeed = 3f;

    // Movement control variables
	Vector2 input;
	bool isMoving = false;
    Rigidbody2D rb;

    // Animation controller
    Animator anim;

    // Called at start
    void Start() {
        anim = GetComponent<Animator>();
        rb = GetComponent<Rigidbody2D>();
    }
	
    // Update is called once per frame
    void Update()
    {
        if(!isMoving){
            input = new Vector2(Input.GetAxisRaw("Horizontal"), Input.GetAxisRaw("Vertical"));
            if(Mathf.Abs(input.x) > Mathf.Abs(input.y)) {
                input.y = 0;
            } else {
                input.x = 0;
            }
            
            if(input != Vector2.zero) {
                // Control Animator
                anim.SetBool("isWalking", true);
                anim.SetFloat("input_x", input.x);
                anim.SetFloat("input_y", input.y);

                // Move character
                Move();
            } else {
                anim.SetBool("isWalking", false);
            }
        }
    }

    /**
    * Move the character smoothly according to the input vector
    */
    public void Move() {
        isMoving = true;

        if (Input.GetAxisRaw("Vertical") > 0) 
            rb.MovePosition(rb.position + Vector2.up * (Time.fixedDeltaTime * walkSpeed));
        else if (Input.GetAxisRaw("Vertical") < 0) 
            rb.MovePosition(rb.position + Vector2.down * (Time.fixedDeltaTime * walkSpeed));
        else if (Input.GetAxisRaw("Horizontal") < 0) 
            rb.MovePosition(rb.position + Vector2.left * (Time.fixedDeltaTime * walkSpeed));
        else if (Input.GetAxisRaw("Horizontal") > 0) 
            rb.MovePosition(rb.position + Vector2.right * (Time.fixedDeltaTime * walkSpeed));
        
        isMoving = false;
    }
}
```
Replacing the movement script with this makes the movement much smoother

**Review by cailafinn — APPROVED** [review]
Looks good to me now, just needs a second quick approval for some misc changes

**Review by Alice-Jaffray — COMMENTED** [review]
tested again looking good

**Pull request merged**
