### PR TITLE
Encourage the player to talk to Ginny

### LINKED ISSUE #126: Player should be encouraged to talk to ginny first.
## Expected Behaviour
Upon game load, the player should be encouraged to talk to ginny. 
## Actual Behaviour
The player just appears in the game space.
## Steps to Reproduce Behaviour
1. Load level one

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
Upon starting the first level, it is suggested that the player talk to Ginny first to get some context of how the game works. This is intentionally left optional, in case the player has already played the game and does not want to skip through so many text boxes. 

**To test:**
1. Start level one and check the text box appears. 

Fixes #126

### CODE REVIEW

**Review by Alice-Jaffray — CHANGES_REQUESTED** [review]
Sherry text box is immediately popping up with 'lorem ipsum'

**Comment by cailafinn** [comment]
> Sherry text box is immediately popping up with 'lorem ipsum'

My mistake, forgot to push the changes that fixed that yesterday :')

**Review by Alice-Jaffray — CHANGES_REQUESTED** [review]
So it's looking fab! I love the touch of having his notebook there! the only problem is that no text is appearing when I go to talk to Ginny, the textbox is appearing but no text - and I'm getting the error IndexOutOfRangeException: Index was outside the bounds of the array.

**Review by Alice-Jaffray — APPROVED** [review]
Fabby dabby do da

**Pull request merged**
