### PR TITLE
Create Level end scene

### LINKED ISSUE #96: Levels Need to End Cleanly
## Expected Behaviour
Upon completing all 10 questions, the player should be presented with a score screen showing how many correct answers they got and how long the level took them. 
## Actual Behaviour
The level does not end. 
## Steps to Reproduce Behaviour
1. Answer all 10 questions.

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
Added assets to be used for the end of case screen
Implemented assets when level ends
Refactored UI controller. 

**To test:**
- Check the quality of the assets
- Test the level end screen appears properly when winning and losing a level. 

**Code review on `.cs` files.**

Fixes #96

### CODE REVIEW

**Review by Alice-Jaffray — COMMENTED** [review]
Assets look super cute!

**Review by Alice-Jaffray — CHANGES_REQUESTED** [review]
It looks fab! But after I've failed a level and then returned to the main menu, when I re-attempt the level the questions I've answered are still not available - is this a fix for a different ticket or this one?

**Comment by cailafinn** [comment]
> It looks fab! But after I've failed a level and then returned to the main menu, when I re-attempt the level the questions I've answered are still not available - is this a fix for a different ticket or this one?

Nope, that's this one, knew there was something I'd forgotten

**Review by Alice-Jaffray — APPROVED** [review]
its starting to come together like a proper game! so excited!!

**Pull request merged**
