### PR TITLE
Updated minimap

### LINKED ISSUE #153: Update Minimap
## Expected Behaviour

Update minimap with new door placement and new room
Add Minimap to conservatory

waiting for #151 to be merged

## Actual Behaviour

Minimap is outdated

## Steps to Reproduce Behaviour
1. Have you seen the minimap recently?

### PR DESCRIPTION
**Pull request by Alice-Jaffray**
**Description of work.**

Minimap has been updated for the doors and rooms

**To test:**

go to each room and check the minimap

Fixes #153

### CODE REVIEW

**Comment by cailafinn** [comment]
If this is a WIP, can it be changed into a draft PR until it's ready for review?

**Review by cailafinn — CHANGES_REQUESTED** [review]
Lots of extra commits here. Could this be rebased onto master?

Otherwise, looks good and works well :)

**Comment by Alice-Jaffray** [comment]
Lol i know I wasn't finished 😄 The other commits came from a rebase so ... lol #imtired

**Comment by cailafinn** [comment]
> Lol i know I wasn't finished 😄 The other commits came from a rebase so ... lol #imtired

Ah, fairs, just saw the notification that the title switched off WIP, my bad :')

**Comment by Alice-Jaffray** [comment]
Created a different pr for this ticket

**Pull request closed without merging**
